config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :books, only: %i[new create index show edit update destroy]
    get 'stats', to: 'pages#stats', as: 'stats'
  end

  resources :search, only: [:index]

  get 'authors/new', to: 'authors#new', as: 'authors_new'
  post 'authors/create', to: 'authors#create', as: 'authors_create'
  get 'authors/show/:id', to: 'authors#show', as: 'author'

  # Q U O T E    R O U T E S
  get 'quotes/new', to: 'quotes#new', as: 'new_quote'
  post 'quotes/create', to: 'quotes#create', as: 'create_quote'

  # N O T E   R O U T E S
  get 'notes/new', to: 'notes#new', as: 'new_note'
  post 'notes/new', to: 'notes#create', as: 'create_note'

  # B O O K   S E A R C H   R O U T E
  post 'search/fetch_books', to: 'search#fetch_books', as: 'fetch'
  post 'search/fetch_book', to: 'search#fetch_book', as: 'fetch_book'

  # S T A T S     R O U T E S
  # has a json at the endpoint
  get 'stats/barchart', to: 'stats#barchart', as: 'barchart'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :users_book

  include PgSearch::Model
  multisearchable against: [:note_text]
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
  end

  def create
    @note = Note.new(note_params)
    authorize @note
    if @note.save
      redirect_to user_book_path(current_user, @note.users_book.book), notice: 'Note added!'
    else
      redirect_to user_book_path(current_user, @note.users_book.book), notice: 'Something went wrong!'
    end
  end

  private

  def note_params
    params.require(:note).permit(:note_text, :page_num, :users_book_id)
  end

end

app/views/notes/_new.html.erb
<%= simple_form_for :note, url: create_note_path, method: :post, id: 'create-note-form', input_html: { class: 'note-form'} do |note_form| %>
  <%= note_form.input :users_book_id, as: :hidden, input_html: { value: users_book.id } %>
  <%#= note_form.input :note_text, as: :text, rows: 40, cols: 120, input_html: { autocomplete: 'off', class: 'tinymce'} %>
  <%= note_form.text_area :note_text, :class => "tinymce", :rows => 10, :cols => 45 %>
  <%= tinymce_assets %>
  <%= tinymce %>
  <%= note_form.input :page_num %>
  <%= note_form.button :submit, "Add Note", class: "btn btn-bookplated note-submit", data: { disable_with: false } %>
<% end %>

app/views/notes/_notes_modal.html.erb
<div class="modal fade" id="new-note-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myLargeModalLabel">Add a Note:</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body" id="new-note-modal-body">
      <%= render 'notes/new', users_book: @users_book %>
      </div>
    </div>
  </div>
</div>