config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :books, only: %i[new create index show edit update destroy]
    get 'stats', to: 'pages#stats', as: 'stats'
  end

  resources :search, only: [:index]

  get 'authors/new', to: 'authors#new', as: 'authors_new'
  post 'authors/create', to: 'authors#create', as: 'authors_create'
  get 'authors/show/:id', to: 'authors#show', as: 'author'

  # Q U O T E    R O U T E S
  get 'quotes/new', to: 'quotes#new', as: 'new_quote'
  post 'quotes/create', to: 'quotes#create', as: 'create_quote'

  # N O T E   R O U T E S
  get 'notes/new', to: 'notes#new', as: 'new_note'
  post 'notes/new', to: 'notes#create', as: 'create_note'

  # B O O K   S E A R C H   R O U T E
  post 'search/fetch_books', to: 'search#fetch_books', as: 'fetch'
  post 'search/fetch_book', to: 'search#fetch_book', as: 'fetch_book'

  # S T A T S     R O U T E S
  # has a json at the endpoint
  get 'stats/barchart', to: 'stats#barchart', as: 'barchart'
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authors_books, dependent: :destroy
  has_many :users_books, dependent: :destroy
  has_many :authors, through: :authors_books

  mount_uploader :photo, PhotoUploader

  include PgSearch::Model
  multisearchable against: [:title]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :users_books
  has_many :books, through:  :users_books
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @books = policy_scope(Book).order(created_at: :desc)
    if params[:query].present?
      results = PgSearch.multisearch(params[:query])
      @authors = [] #only authors with books in user library
      @books = [] #only books with query in title
      @books_of_authors = [] #books of an author, when query is author's name
      @quotes = [] #quotes with query in quote_text
      @notes = [] #notes with query in note_text
      results.each do |result|
        if result[:searchable_type] == "Author"
          author = Author.find(result[:searchable_id])
          current_user.users_books.each do |users_book|
            @authors << author if users_book.book.author_ids.include? author.id
          end
          @authors.uniq!
        elsif result[:searchable_type] == "Book"
          book = Book.find(result[:searchable_id])
          @books << book if current_user.book_ids.include? book.id
        elsif result[:searchable_type] == "Quote"
          quote = Quote.find(result[:searchable_id])
          @quotes << quote if quote.users_book.user_id == current_user.id
        elsif result[:searchable_type] == "Note"
          note = Note.find(result[:searchable_id])
          @notes << note if note.users_book.user_id == current_user.id
        end
      end
      unless @authors.empty?
        @authors.each do |author|
          author.books.each { |book| @books_of_authors << book if current_user.book_ids.include? book.id }
        end
      end
    end
    @partial = whitelisted_partial || 'grid'
    @query = params[:query]
  end

  def fetch_books
    skip_authorization
    scrape_results = GoodreadsScrapeService.new(params[:title])
    @top_three = scrape_results.fetchSearchResults
  end

  def fetch_book
    skip_authorization
    scrape_results = GoodreadsScrapeService.new(params[:title])

    # Only scrape if book doesn't exist in db!

    @details = scrape_results.fetchBookDetails(params["book"])
    book_exists = Book.find_by(title: params[:title])
    if book_exists && (book_exists.authors.first.full_name == @details.last[:full_name])
      @book = Book.find_by(title: @details.first[:title])
      @author = @book.authors.first
    else
      @book = Book.new(@details.first)
      author = Author.create(@details.last)
      @book.authors << author
      @book.save
    end
    users_book = UsersBook.new
    users_book.user = current_user
    users_book.book = @book
    if users_book.save
      redirect_to root_path
    end
    # binding.pry
  end

  private

  def whitelisted_partial
    %w(grid list).detect { |str| str == params[:view] }
  end
end

app/views/search/_fetched_book.html.erb
<div class="modal-ajax-content">
  <p><%= @details.first[:pages] %></p>
  <p><%= @details.first[:year_published] %></p>
  <p><%= @details.first[:isbn] %></p>
  <p><%= @details.first[:title] %></p>
</div>

app/views/search/_fetched_books_modal.html.erb
<div class="modal fade" id="fetched-books" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myLargeModalLabel">Search results:</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body" id="fetched-books-modal-body">
      <%#= render 'notes/new', users_book: @users_book %>
      </div>
    </div>
  </div>
</div>

app/views/search/_fetched_list.html.erb
<div class="modal-ajax-content">
  <% @top_three.each do |book| %>
    <div class="scrape-result-card">
      <div class="scrape-cover">
        <% if book[:cover_url] == "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/nophoto/book/111x148._SX50_.png" %>
          <%= image_tag 'http://via.placeholder.com/45x75' %>
        <% else %>
          <%= image_tag book[:cover_url] %>
        <% end %>
      </div>
      <div class="scrape-details">
        <%= link_to fetch_book_path(book: book), method: :post do %>
          <h3><%= book[:title] %></h3>
        <% end %>
        <p>by <%= book[:author] %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/search/_grid.html.erb
<div class="row">
  <% if @books.empty? %>
    <p>You don't seem to have read any books yet! Add one?</p>
  <% else %>
    <% @books.each do |book| %>
      <div class="col-6 col-lg-2">
        <%= link_to user_book_path(current_user, book) do %>
          <%= image_tag photo_or_placeholder(book), class: 'book-cover' %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/search/_list.html.erb
<table class="list-display">
  <tr class="headers">
    <th class="th-cover">Cover</th>
    <th class="th-title">Title</th>
    <th class="th-author">Author</th>
    <th class="th-date-read">Date Read</th>
    <th class="th-pages">Pages</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_book_path(current_user, book) do %>
          <%= image_tag photo_or_placeholder(book), class: 'book-cover-list' %>
        <% end %>
      </td>
      <td>
        <%= link_to user_book_path(current_user, book), class: 'link' do %>
          <%= book.title %>
        <% end %>
      </td>
      <td>
        <% book.authors.each do |author| %>
          <%= link_to author_path(author), class: 'link' do %>
            <%= author.full_name %>
          <% end %>
        <% end %>
      </td>
      <!-- get the UsersBook association for book -->
      <% book.users_book_ids.each do |users_book_id| %>
        <% if current_user.users_book_ids.include?  users_book_id %>
          <% @users_book = UsersBook.find(users_book_id) %>
        <% end %>
      <% end %>
      <!--  -->
      <td>
        <% if @users_book.date_read %>
          <%= Time.at(@users_book.date_read).strftime("%d %B, %Y") %>
        <% else %>
          <p>-</p>
        <% end %>
      </td>
      <td><%= book.pages %></td>
    </tr>
  <% end %>
</table>

app/views/search/fetch_book.js.erb
function populateModal() {
  const modalBody = document.getElementById('fetched-books-modal-body');
  modalBody.innerHTML = '<%= j render "search/fetched_list", top_three: @top_three %>';
}

populateModal();

app/views/search/fetch_books.js.erb
function populateModal() {
  const modalBody = document.getElementById('fetched-books-modal-body');
  modalBody.innerHTML = '<%= j render "search/fetched_list", top_three: @top_three %>';
}

populateModal();

app/views/search/index.html.erb
<div class="container">

  <!-- Classic tabs -->
  <div class="classic-tabs quotes-and-notes search-results">

    <ul class="nav tabs-cyan" id="myClassicTabShadow" role="tablist">
      <li class="nav-item">
        <a class="nav-link active show" id="profile-tab-classic-shadow" data-toggle="tab" href="#profile-classic-shadow"
          role="tab" aria-controls="profile-classic-shadow" aria-selected="true">
          <h4>
            Books (<%= @books.size %>)
          </h4>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="follow-tab-classic-shadow" data-toggle="tab" href="#classic-authors"
          role="tab" aria-controls="follow-classic-shadow" aria-selected="false">
          <h4>
            Authors (<%= @authors.size %>)
          </h4>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="follow-tab-classic-shadow" data-toggle="tab" href="#classic-quotes"
          role="tab" aria-controls="follow-classic-shadow" aria-selected="false">
          <h4>
            Quotes (<%= @quotes.size %>)
          </h4>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="follow-tab-classic-shadow" data-toggle="tab" href="#classic-notes"
          role="tab" aria-controls="follow-classic-shadow" aria-selected="false">
          <h4>
            Notes (<%= @notes.size %>)
          </h4>
        </a>
      </li>
    </ul>

    <div class="tab-content card" id="myClassicTabContentShadow">
      <div class="tab-pane fade active show" id="profile-classic-shadow" role="tabpanel" aria-labelledby="profile-tab-classic-shadow">

          <div class="filters">
            <div class="filter-display">
              <%= link_to search_index_path(current_user, view: 'list', query: @query), class: 'list-view' do %>
                <i class="fas fa-list"></i>
              <% end %>
              <%= link_to search_index_path(current_user, view: 'grid', query: @query), class: 'grid-view' do %>
                <i class="fas fa-th-large"></i>
              <% end %>
            </div>
            <i class="fas fa-filter"></i>
          </div>
          <%= render @partial, locals: {books: @books} %>

      </div>
      <div class="tab-pane fade" id="classic-authors" role="tabpanel" aria-labelledby="follow-tab-classic-shadow">
        <div class="author-results">
          <% if @authors.empty? %>
            <p>No author results.</p>
          <% else %>
            <p><%= @authors.size %> results</p>
            <% @authors.each do |author| %>
              <div class="author-card">
                <div class="author-details">
                  <h4>
                    <%= link_to author, class: 'link' do %>
                    <%= author.full_name %>
                    <% end %>
                  </h4>

                  <!-- get the number of books by the author that the user has saved in their library -->
                  <% num_authors_books = 0 %>
                  <% author.books.each {|book| num_authors_books += 1 if @books_of_authors.include? book} %>

                  <p>You have <%= num_authors_books %> books</p>
                </div>
                <div class="author-life">
                  <p>
                    <%= author.birth_year %>
                    -
                    <% if author.death_year.nil? %>
                      present
                    <% else %>
                      <%= author.death_year %>
                    <% end %>
                  </p>
                </div>
                <div class="author-books">
                  <% unless author.authors_books.empty? %>
                    <% author.authors_books.each do |authors_book| %>
                      <% if current_user.book_ids.include? authors_book.book.id %>
                        <%= link_to user_book_path(current_user, authors_book.book) do %>
                          <%= image_tag photo_or_placeholder(authors_book.book), class: 'book-cover-sm' %>
                        <% end %>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="tab-pane fade" id="classic-quotes" role="tabpanel" aria-labelledby="follow-tab-classic-shadow">
        <div class="quote-results">
          <% if !@quotes.present? || @quotes.empty? %>
            <p>No quote results.</p>
          <% else %>
            <p><%= @quotes.size %> results</p>
            <% @quotes.each do |quote| %>
              <div class="quote-card">
                <p class="quote-text">"<%= quote.quote_text %>"</p>
                <p>-

                  <%= quote.users_book.book.authors.first.full_name %>

                </p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="tab-pane fade" id="classic-notes" role="tabpanel" aria-labelledby="follow-tab-classic-shadow">
        <div class="note-results">
          <% if !@notes.present? || @notes.empty? %>
            <p>No note results.</p>
          <% else %>
            <p><%= @notes.size %> results</p>
            <% @notes.each do |note| %>
              <div class="note-card">
                <p class="note-text"><%= raw note.note_text %></p>
                <p><%= note.page_num if note.page_num %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
  <!-- Classic tabs -->



</div>