config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :books, only: %i[new create index show edit update destroy]
    get 'stats', to: 'pages#stats', as: 'stats'
  end

  resources :search, only: [:index]

  get 'authors/new', to: 'authors#new', as: 'authors_new'
  post 'authors/create', to: 'authors#create', as: 'authors_create'
  get 'authors/show/:id', to: 'authors#show', as: 'author'

  # Q U O T E    R O U T E S
  get 'quotes/new', to: 'quotes#new', as: 'new_quote'
  post 'quotes/create', to: 'quotes#create', as: 'create_quote'

  # N O T E   R O U T E S
  get 'notes/new', to: 'notes#new', as: 'new_note'
  post 'notes/new', to: 'notes#create', as: 'create_note'

  # B O O K   S E A R C H   R O U T E
  post 'search/fetch_books', to: 'search#fetch_books', as: 'fetch'
  post 'search/fetch_book', to: 'search#fetch_book', as: 'fetch_book'

  # S T A T S     R O U T E S
  # has a json at the endpoint
  get 'stats/barchart', to: 'stats#barchart', as: 'barchart'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="new-author-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myLargeModalLabel">Add an Author:</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body" id="new-author-modal-body">
      <%= render 'authors/new' %>

      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1 class="logo">bookplated.</h1>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% unless controller.action_name == 'new' %>
    <%= form_tag search_index_path, method: :get, class: 'search-form' do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search your library..."
      %>
      <button type="submit">
        <i class="fas fa-search"></i>
      </button>
    <% end %>
  <% end %>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>



        <!-- L I N K   to   N E W    B O O K -->
        <li class="nav-item active">
          <%= link_to new_user_book_path(current_user), class: "nav-link" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </li>
        <!-- L I N K   to   S T A T S -->
        <li class="nav-item active">
          <%= link_to user_stats_path(current_user), class: "nav-link" do %>
            <i class="fas fa-signal"></i>
          <% end %>
        </li>


        <li class="nav-item dropdown">
          <span class="dropdown-toggle" id="navbarDropdown", data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">account</span>
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "my books", user_books_path(current_user), class: "dropdown-item" %>
            <%= link_to "my stats", user_stats_path(current_user), class: "dropdown-item" %>
            <%= link_to "log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>