config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :books, only: %i[new create index show edit update destroy]
    get 'stats', to: 'pages#stats', as: 'stats'
  end

  resources :search, only: [:index]

  get 'authors/new', to: 'authors#new', as: 'authors_new'
  post 'authors/create', to: 'authors#create', as: 'authors_create'
  get 'authors/show/:id', to: 'authors#show', as: 'author'

  # Q U O T E    R O U T E S
  get 'quotes/new', to: 'quotes#new', as: 'new_quote'
  post 'quotes/create', to: 'quotes#create', as: 'create_quote'

  # N O T E   R O U T E S
  get 'notes/new', to: 'notes#new', as: 'new_note'
  post 'notes/new', to: 'notes#create', as: 'create_note'

  # B O O K   S E A R C H   R O U T E
  post 'search/fetch_books', to: 'search#fetch_books', as: 'fetch'
  post 'search/fetch_book', to: 'search#fetch_book', as: 'fetch_book'

  # S T A T S     R O U T E S
  # has a json at the endpoint
  get 'stats/barchart', to: 'stats#barchart', as: 'barchart'
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authors_books, dependent: :destroy
  has_many :users_books, dependent: :destroy
  has_many :authors, through: :authors_books

  mount_uploader :photo, PhotoUploader

  include PgSearch::Model
  multisearchable against: [:title]
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :fetch_book, only: %i[show edit update]

  def index
    @books = policy_scope(current_user.books).order(created_at: :desc)
    @partial = whitelisted_partial || 'grid'
  end

  def show
    authorize @book
    @quote = Quote.new
    @users_book = @book.users_books.where(:user_id == current_user.id).first
  end

  def new
    @book = Book.new
    authorize @book
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      @users_book = UsersBook.new
      @users_book.user = current_user
      @users_book.book = @book
    else
      render 'new'
    end
    params[:book][:author_ids].each do |id|
      unless id.empty?
        authors_book = AuthorsBook.new
        authors_book.book = @book
        authors_book.author = Author.find(id)
        authors_book.save
      end
    end
    if @users_book.save
      redirect_to user_books_path
    else
      render 'new'
    end
    authorize @book
  end

  def edit
  end

  def update
    authorize @book

    if params[:photo].present?
      preloaded = Cloudinary::PreloadedFile.new(params[:photo])
      raise "Invalid upload signature" if !preloaded.valid?
      @book.photo = preloaded.identifier
    end
  end

  private

  def fetch_book
    @book = Book.find(params[:id])
    authorize @book
  end

  def book_params
    params.require(:book).permit(:title, :year_published, :pages, :cover, :isbn, :users_book_id, :author_ids, :photo)
  end

  def whitelisted_partial
    %w(grid list).detect { |str| str == params[:view] }
  end
end

app/helpers/book_helper.rb
module BookHelper
  def photo_or_placeholder(book)
    if book.photo_url.present?
      cl_image_path book.photo_url
    else
      'http://via.placeholder.com/140x200'
      # 'https://res.cloudinary.com/djkvtunck/image/upload/v1568216783/j54mfn75mceuggabjkkt.png'
    end
  end
end

app/views/books/_edit_cover_form.html.erb
<div class="edit-cover-form">
  <div class="cover-preview">
    <%= image_tag photo_or_placeholder(book), class: 'book-cover' %>
  </div>
  <%= simple_form_for @book, url: user_book_path(current_user, @book), method: :patch do |f| %>
    <%= f.input :title %>
    <%#= f.input :photo,
              input_html:
                { class: 'hidden',
                  id: 'photo-input'
                },
              label_html:
                { class: 'upload-photo'},
              label: 'Upload a new Book Cover:' %>


    <%#= cl_image_upload_tag(
      :photo,
      :tags => "directly_uploaded",
      :crop => :limit, :width => 140, :height => 200,
      :eager => [{ :crop => :fill, :width => 150, :height => 100 }],
      :html => { :style => "margin-top: 30px" }
    ) %>

    <%#= f.cl_image_upload(:photo) %>
    <%#= f.input :photo_cache, as: :hidden %>

    <%= f.file_field :photo %>
    <%= f.hidden_field(:photo_cache) %>
    <%#= hidden_field_tag :direct, params[:direct] %>


    <%= f.button :submit, 'Change Cover', class: 'btn btn-bookplated' %>
  <% end %>
</div>

app/views/books/_edit_cover_modal.html.erb
<div class="modal fade" id="edit-cover-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myLargeModalLabel">Edit Book Cover:</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body" id="new-quote-modal-body">
        <%= render 'edit_cover_form', book: @book %>

      </div>
    </div>
  </div>
</div>

app/views/books/_grid.html.erb
  <div class="row">
    <% if @books.empty? %>
      <p>You don't seem to have read any books yet! Add one?</p>
    <% else %>
      <% @books.each do |book| %>
        <div class="col-4 col-sm-4 col-md-3 col-lg-2">
          <%= link_to user_book_path(current_user, book) do %>
            <% if book.cover.nil? %>
              <%= image_tag photo_or_placeholder(book), class: 'book-cover' %>
            <% else %>
              <%= image_tag(book.cover, class: 'book-cover') %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/books/_list.html.erb
<table class="list-display">
  <tr class="headers">
    <th class="th-cover">Cover</th>
    <th class="th-title">Title</th>
    <th class="th-author">Author</th>
    <th class="th-date-read">Date Read</th>
    <th class="th-pages">Pages</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_book_path(current_user, book) do %>
        <%# raise %>
          <% if book.cover.nil? %>
            <%= image_tag photo_or_placeholder(book), class: 'book-cover-list' %>
          <% else %>
            <%= image_tag(book.cover, height: "200px") %>
          <% end %>
        <% end %>
      </td>
      <td>
        <%= link_to user_book_path(current_user, book), class: 'link' do %>
          <%= book.title %>
        <% end %>
      </td>
      <td>
        <% book.authors.each do |author| %>
          <%= link_to author_path(author), class: 'link' do %>
            <%= author.full_name %>
          <% end %>
        <% end %>
      </td>
      <!-- get the UsersBook association for book -->
      <% book.users_book_ids.each do |users_book_id| %>
        <% if current_user.users_book_ids.include?  users_book_id %>
          <% @users_book = UsersBook.find(users_book_id) %>
        <% end %>
      <% end %>
      <!--  -->
      <td>
        <% if @users_book.date_read %>
          <%= Time.at(@users_book.date_read).strftime("%d %B, %Y") %>
        <% else %>
          <p>-</p>
        <% end %>
      </td>
      <td><%= book.pages %></td>
    </tr>
  <% end %>
</table>

app/views/books/_new_book_form.html.erb
<%= simple_form_for @book, url: user_books_path, method: :post do |f| %>
  <%= f.association :authors, label_method: :full_name, input_html: { class: 'select2' } %>

  <p class="btn btn-bookplated" data-toggle="modal" data-target="#new-author-modal">New Author</p>

  <%= f.input :title %>
  <%= f.input :year_published %>
  <%= f.input :pages %>
  <%= f.input :isbn %>

  <%= f.input :photo,
              input_html:
                { class: 'hidden',
                  id: 'photo-input'
                },
              label_html:
                { class: 'upload-photo'},
              label: 'Upload a photo' %>




  <%= image_tag "", width: 300, class: "hidden", id: "photo-preview" %>
  <%= f.input :photo_cache, as: :hidden %>

  <%= f.button :submit, "Add Book", class: 'btn btn-bookplated' %>
<% end %>

  <%= render 'shared/modal'%>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div class="container">
  <div class="filters">
    <div class="filter-display">
      <%= link_to user_books_path(view: 'list') do %>
        <i class="fas fa-list"></i>
      <% end %>
      <%= link_to user_books_path(view: 'grid') do %>
        <i class="fas fa-th-large"></i>
      <% end %>
    </div>
    <i class="fas fa-filter"></i>
  </div>
  <%= render @partial, locals: {books: @books} %>
</div>

app/views/books/new.html.erb
<div class="container new-book-container">
  <div class="new-book-scraper">
    <h3>Add a Book:</h3>
    <%= form_tag fetch_path, method: :post, remote: :true do %>
      <div class="form-inputs">
        <%= text_field_tag :title, nil, placeholder: 'Search for a title' %>
      </div>
      <div id="fetch-books" class="form-action">
        <%#= submit_tag "Search", class: 'btn btn-bookplated'%>
        <%= submit_tag "Search", class: "btn btn-bookplated", data: { toggle: 'modal', target: "#fetched-books"} %>
      </div>
    <% end %>
    <%= render 'search/fetched_books_modal' %>
    <%= link_to 'Add a book manually?', class: 'link' %>
  </div>
  <%#= render 'new_book_form' %>
</div>

app/views/books/show.html.erb
<div class="container show-container">
  <div class="book-details">
    <div class="book-cover-container">
      <% if @book.cover.nil? %>
        <%= image_tag photo_or_placeholder(@book), class: 'book-cover' %>
      <% else %>
        <%= image_tag(@book.cover, class: 'book_cover', height: "200px")  %>
      <% end %>
      <span class="edit-cover" data-toggle="modal" data-target="#edit-cover-modal">edit</span>
      <%= render 'books/edit_cover_modal', book: @book %>

    </div>
    <div class="book-info">
      <div class="title-author">
        <h1><%= @book.title %></h1>
        <p>by
          <%= link_to @book.authors.first, class: 'link' do %>
            <%= @book.authors.first.full_name %>
          <% end %>
        </p>
      </div>

      <div class="book-stats">
        <table>
          <tr>
            <th>Published</th>
            <th>Pages</th>
            <th>Read</th>
            <th>Own</th>
          </tr>
          <tr>
            <!-- Y E A R   P U B L I S H E D -->
            <td class="book-info-stat">
              <%= @book.year_published if @book.year_published %>
            </td>

            <!-- N U M    P A G E S  -->
            <td class="book-info-stat">
              <%= @book.pages if @book.pages %>
            </td>

            <!-- D A T E    R E A D  -->
            <td class="book-info-stat <% if @users_book.date_read %>read<% else %>unread<% end %>">
              <% if @users_book.date_read.nil? %>
                unread
              <% else %>
                <%= Time.at(@users_book.date_read).strftime("%d %B, %Y") %>
              <% end %>
            </td>

            <!-- O W N E D    S T A T U S -->
            <td class="book-info-stat <% if @users_book.owned %>owned<% else %>unowned<% end %>">
              <% if @users_book.owned.nil? %>
                don't own
              <% else %>
                own
              <% end %>
            </td>

          </tr>
        </table>
      </div>


    </div>
  </div>


  <!-- Classic tabs -->
  <div class="classic-tabs quotes-and-notes">

    <ul class="nav" id="myClassicTabShadow" role="tablist">
      <li class="nav-item">
        <a class="nav-link active show" id="profile-tab-classic-shadow" data-toggle="tab" href="#profile-classic-shadow"
          role="tab" aria-controls="profile-classic-shadow" aria-selected="true">
          <h4>
            Quotes
            <i class="fas fa-plus" data-toggle="modal" data-target="#new-quote-modal"></i>
            <%= render 'quotes/quotes_modal', users_book: @users_book %>
          </h4>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="notes-tab-classic-shadow" data-toggle="tab" href="#notes-classic-shadow"
          role="tab" aria-controls="notes-classic-shadow" aria-selected="false">
          <h4>
            Notes
            <i class="fas fa-plus" id="notes-tab-plus" data-toggle="modal" data-target="#new-note-modal"></i>
            <%= render 'notes/notes_modal', users_book: @users_book %>
          </h4>
        </a>
      </li>
    </ul>

    <div class="tab-content card" id="myClassicTabContentShadow">
      <div class="tab-pane fade active show" id="profile-classic-shadow" role="tabpanel" aria-labelledby="profile-tab-classic-shadow">

        <div class="quotes-or-notes">
          <% if @users_book.quotes.empty? %>
            <p class="italic">You don't have any quotes yet!</p>
          <% else %>
            <% @users_book.quotes.reverse.each do |quote| %>
              <div class="quote-card">
                <p><span class="quote-text">"<%= quote.quote_text %>"</span> - <span class="page-num"><% if quote.page_num %>page <%= quote.page_num %><% end %></span></p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="tab-pane fade" id="notes-classic-shadow" role="tabpanel" aria-labelledby="notes-tab-classic-shadow">

        <div class="quotes-or-notes">

          <% if @users_book.notes.empty? %>
            <p class="italic">You don't have any notes yet!</p>
          <% else %>
            <% @users_book.notes.reverse.each do |note| %>
              <p><span class="quote-text"><%= sanitize note.note_text %></span></p>
            <% end %>
          <% end %>

        </div>
      </div>
    </div>

  </div>
  <!-- Classic tabs -->



</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>